name: Docs
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
      - uses: julia-actions/cache@v2
      #next line is here to support headless running of GLMakie (github server has no monitor on it...)
      - name: Install binary dependencies
        run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
      - uses: julia-actions/julia-buildpkg@v1
      - run: ls -R docs/src
      - run: test -f docs/src/assets/Tutorial_Dataset.png && echo "FOUND image" || (echo "MISSING image"; exit 1)
      - run: sed -n '1,200p' docs/src/tutorial.md
      - uses: julia-actions/julia-docdeploy@v1
        with:
          prefix: xvfb-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key